"""Add multi upi support

Revision ID: 5a5b4dac488a
Revises: 942bf52c9d5d
Create Date: 2026-03-11 22:18:40.213177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5b4dac488a'
down_revision: Union[str, None] = '942bf52c9d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upi_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upi_id', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upi_accounts_id'), 'upi_accounts', ['id'], unique=False)
    op.add_column('bills', sa.Column('upi_account_id', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('upi_id_used', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'bills', 'upi_accounts', ['upi_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'upi_id_used')
    op.drop_column('bills', 'upi_account_id')
    op.drop_index(op.f('ix_upi_accounts_id'), table_name='upi_accounts')
    op.drop_table('upi_accounts')
    # ### end Alembic commands ###
